"""NC65 accounts-payable mirror — bills, lines, and the sync run log.

NC is the book of record for payable balances, so `NcApBillLine.money_bal` is
the authoritative open amount; our own `ap_invoices.paid_amount` is not
(payments happen in NC and never flow back — see the spec, §10.1).

These models mirror the physical tables created by 0033_nc_ap_mirror column for
column. Keep them that way: a mirror model that drifts from its table is a bug
that only shows up as a 500 in production.
"""
import uuid
from datetime import datetime
from decimal import Decimal

from sqlalchemy import Boolean, DateTime, ForeignKey, Integer, Numeric, String, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base, TimestampMixin, UUIDPrimaryKey

RUNNING = "running"
SUCCESS = "success"
FAILED = "failed"

# Trade types that discriminate the two worlds of NC payables (spec §9.2).
TRADE_MANUAL = "F1-Cxx-017"     # keyed by finance — miscellaneous purchases, EPMS spend
TRADE_SUPPLY = "D1"             # generated by the supply chain from a settlement


class NcApBill(UUIDPrimaryKey, TimestampMixin, Base):
    __tablename__ = "nc_ap_bills"

    nc_pk: Mapped[str] = mapped_column(String(25), nullable=False, unique=True)
    bill_no: Mapped[str] = mapped_column(String(40), nullable=False, index=True)
    trade_type: Mapped[str | None] = mapped_column(String(30), nullable=True)
    bill_type: Mapped[str | None] = mapped_column(String(20), nullable=True)
    src_syscode: Mapped[int | None] = mapped_column(Integer, nullable=True)
    bill_class: Mapped[str | None] = mapped_column(String(10), nullable=True)
    bill_year: Mapped[str | None] = mapped_column(String(4), nullable=True)
    bill_period: Mapped[str | None] = mapped_column(String(2), nullable=True)
    bill_date: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    approve_date: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    effect_date: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    bill_status: Mapped[int | None] = mapped_column(Integer, nullable=True)
    approve_status: Mapped[int | None] = mapped_column(Integer, nullable=True)
    supplier_pk: Mapped[str | None] = mapped_column(String(25), nullable=True)
    supplier_code: Mapped[str | None] = mapped_column(String(50), nullable=True, index=True)
    supplier_name: Mapped[str | None] = mapped_column(String(200), nullable=True)
    currency: Mapped[str | None] = mapped_column(String(10), nullable=True)
    money: Mapped[Decimal | None] = mapped_column(Numeric(18, 2), nullable=True)
    local_money: Mapped[Decimal | None] = mapped_column(Numeric(18, 2), nullable=True)
    bill_maker: Mapped[str | None] = mapped_column(String(25), nullable=True)
    nc_ts: Mapped[str] = mapped_column(String(19), nullable=False, index=True)
    synced_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    lines: Mapped[list["NcApBillLine"]] = relationship(
        back_populates="bill", cascade="all, delete-orphan", passive_deletes=True)

    @property
    def is_finance_keyed(self) -> bool:
        """True for the hand-entered world (§9.2) — where EPMS spend lands."""
        return self.trade_type == TRADE_MANUAL


class NcApBillLine(Base):
    __tablename__ = "nc_ap_bill_lines"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True,
                                          default=uuid.uuid4)
    bill_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("nc_ap_bills.id", ondelete="CASCADE"),
        nullable=False, index=True)
    nc_pk: Mapped[str] = mapped_column(String(25), nullable=False, unique=True)
    row_no: Mapped[int | None] = mapped_column(Integer, nullable=True)
    bill_no: Mapped[str] = mapped_column(String(40), nullable=False)
    bill_date: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    bill_year: Mapped[str | None] = mapped_column(String(4), nullable=True)
    bill_period: Mapped[str | None] = mapped_column(String(2), nullable=True)

    money_cr: Mapped[Decimal | None] = mapped_column(Numeric(18, 2), nullable=True)
    money_bal: Mapped[Decimal | None] = mapped_column(Numeric(18, 2), nullable=True)
    notax_cr: Mapped[Decimal | None] = mapped_column(Numeric(18, 2), nullable=True)
    local_money_cr: Mapped[Decimal | None] = mapped_column(Numeric(18, 2), nullable=True)

    invoice_no: Mapped[str | None] = mapped_column(String(100), nullable=True)
    invoice_no_norm: Mapped[str | None] = mapped_column(String(100), nullable=True, index=True)
    purchase_order: Mapped[str | None] = mapped_column(String(60), nullable=True, index=True)
    settle_no: Mapped[str | None] = mapped_column(String(60), nullable=True)
    contract_no: Mapped[str | None] = mapped_column(String(60), nullable=True)
    subject_code: Mapped[str | None] = mapped_column(String(30), nullable=True)
    cost_center: Mapped[str | None] = mapped_column(String(30), nullable=True)
    dept_pk: Mapped[str | None] = mapped_column(String(25), nullable=True)
    dept_code: Mapped[str | None] = mapped_column(String(30), nullable=True)
    project: Mapped[str | None] = mapped_column(String(30), nullable=True)
    material_pk: Mapped[str | None] = mapped_column(String(25), nullable=True)
    supplier_pk: Mapped[str | None] = mapped_column(String(25), nullable=True)
    supplier_code: Mapped[str | None] = mapped_column(String(50), nullable=True, index=True)
    supplier_name: Mapped[str | None] = mapped_column(String(200), nullable=True)
    pay_term_pk: Mapped[str | None] = mapped_column(String(25), nullable=True)
    tax_rate: Mapped[Decimal | None] = mapped_column(Numeric(9, 4), nullable=True)
    scomment: Mapped[str | None] = mapped_column(String(500), nullable=True)
    src_bill_type: Mapped[str | None] = mapped_column(String(20), nullable=True)
    top_bill_type: Mapped[str | None] = mapped_column(String(20), nullable=True)
    nc_ts: Mapped[str] = mapped_column(String(19), nullable=False)
    synced_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    bill: Mapped[NcApBill] = relationship(back_populates="lines")


class NcApSyncRun(UUIDPrimaryKey, TimestampMixin, Base):
    __tablename__ = "nc_ap_sync_runs"

    mode: Mapped[str] = mapped_column(String(15), nullable=False)      # full | incremental
    status: Mapped[str] = mapped_column(String(10), nullable=False, default=RUNNING, index=True)
    started_by: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    started_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    finished_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    watermark_from: Mapped[str | None] = mapped_column(String(19), nullable=True)
    watermark_to: Mapped[str | None] = mapped_column(String(19), nullable=True)
    bills_seen: Mapped[int] = mapped_column(Integer, nullable=False, default=0, server_default="0")
    bills_upserted: Mapped[int] = mapped_column(Integer, nullable=False, default=0, server_default="0")
    lines_upserted: Mapped[int] = mapped_column(Integer, nullable=False, default=0, server_default="0")
    lines_deleted: Mapped[int] = mapped_column(Integer, nullable=False, default=0, server_default="0")
    tie_out_ok: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    tie_out: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    error: Mapped[str | None] = mapped_column(Text, nullable=True)
