"""NC65 accounts-payable mirror — bills, lines, and the sync run log.

NC is the book of record for payable balances, so `NcApBillLine.money_bal` is
the authoritative open amount; our own `ap_invoices.paid_amount` is not
(payments happen in NC and never flow back — see the spec, §10.1).

These models mirror the physical tables created by 0033_nc_ap_mirror column for
column. Keep them that way: a mirror model that drifts from its table is a bug
that only shows up as a 500 in production.
"""
import uuid
from datetime import date, datetime
from decimal import Decimal

from sqlalchemy import (Boolean, Date, DateTime, ForeignKey, Integer, Numeric,
                        String, Text)
from sqlalchemy.dialects.postgresql import ARRAY, JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base, TimestampMixin, UUIDPrimaryKey

RUNNING = "running"
SUCCESS = "success"
FAILED = "failed"

# A payable NC actually stands behind. Verified 2026-09-22: of 11,805 bills at
# (1, 1), 11,393 carry payments; of the 609 at any other combination, 31 do.
# Everything else is an abandoned draft, an unapproved duplicate, or a void —
# and 35,483,410.06 of "open balance" sits on them. Every derived layer must
# apply this; the MIRROR deliberately does not, so the discarded documents stay
# visible and countable.
BILL_STATUS_EFFECTIVE = 1
APPROVE_STATUS_EFFECTIVE = 1
EFFECTIVE_SQL = "b.bill_status = 1 and b.approve_status = 1"

# Trade types that discriminate the two worlds of NC payables (spec §9.2).
TRADE_MANUAL = "F1-Cxx-017"     # keyed by finance — miscellaneous purchases, EPMS spend
TRADE_SUPPLY = "D1"             # generated by the supply chain from a settlement


class NcApBill(UUIDPrimaryKey, TimestampMixin, Base):
    __tablename__ = "nc_ap_bills"

    nc_pk: Mapped[str] = mapped_column(String(25), nullable=False, unique=True)
    bill_no: Mapped[str] = mapped_column(String(40), nullable=False, index=True)
    trade_type: Mapped[str | None] = mapped_column(String(30), nullable=True)
    bill_type: Mapped[str | None] = mapped_column(String(20), nullable=True)
    src_syscode: Mapped[int | None] = mapped_column(Integer, nullable=True)
    bill_class: Mapped[str | None] = mapped_column(String(10), nullable=True)
    bill_year: Mapped[str | None] = mapped_column(String(4), nullable=True)
    bill_period: Mapped[str | None] = mapped_column(String(2), nullable=True)
    bill_date: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    approve_date: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    effect_date: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    bill_status: Mapped[int | None] = mapped_column(Integer, nullable=True)
    approve_status: Mapped[int | None] = mapped_column(Integer, nullable=True)
    supplier_pk: Mapped[str | None] = mapped_column(String(25), nullable=True)
    supplier_code: Mapped[str | None] = mapped_column(String(50), nullable=True, index=True)
    supplier_name: Mapped[str | None] = mapped_column(String(200), nullable=True)
    currency: Mapped[str | None] = mapped_column(String(10), nullable=True)
    money: Mapped[Decimal | None] = mapped_column(Numeric(18, 2), nullable=True)
    local_money: Mapped[Decimal | None] = mapped_column(Numeric(18, 2), nullable=True)
    bill_maker: Mapped[str | None] = mapped_column(String(25), nullable=True)
    nc_ts: Mapped[str] = mapped_column(String(19), nullable=False, index=True)
    synced_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    lines: Mapped[list["NcApBillLine"]] = relationship(
        back_populates="bill", cascade="all, delete-orphan", passive_deletes=True)

    @property
    def is_finance_keyed(self) -> bool:
        """True for the hand-entered world (§9.2) — where EPMS spend lands."""
        return self.trade_type == TRADE_MANUAL


class NcApBillLine(Base):
    __tablename__ = "nc_ap_bill_lines"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True,
                                          default=uuid.uuid4)
    bill_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("nc_ap_bills.id", ondelete="CASCADE"),
        nullable=False, index=True)
    nc_pk: Mapped[str] = mapped_column(String(25), nullable=False, unique=True)
    row_no: Mapped[int | None] = mapped_column(Integer, nullable=True)
    bill_no: Mapped[str] = mapped_column(String(40), nullable=False)
    bill_date: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    bill_year: Mapped[str | None] = mapped_column(String(4), nullable=True)
    bill_period: Mapped[str | None] = mapped_column(String(2), nullable=True)

    money_cr: Mapped[Decimal | None] = mapped_column(Numeric(18, 2), nullable=True)
    money_bal: Mapped[Decimal | None] = mapped_column(Numeric(18, 2), nullable=True)
    notax_cr: Mapped[Decimal | None] = mapped_column(Numeric(18, 2), nullable=True)
    local_money_cr: Mapped[Decimal | None] = mapped_column(Numeric(18, 2), nullable=True)

    invoice_no: Mapped[str | None] = mapped_column(String(100), nullable=True)
    invoice_no_norm: Mapped[str | None] = mapped_column(String(100), nullable=True, index=True)
    purchase_order: Mapped[str | None] = mapped_column(String(60), nullable=True, index=True)
    settle_no: Mapped[str | None] = mapped_column(String(60), nullable=True)
    contract_no: Mapped[str | None] = mapped_column(String(60), nullable=True)
    subject_code: Mapped[str | None] = mapped_column(String(30), nullable=True)
    cost_center: Mapped[str | None] = mapped_column(String(30), nullable=True)
    dept_pk: Mapped[str | None] = mapped_column(String(25), nullable=True)
    dept_code: Mapped[str | None] = mapped_column(String(30), nullable=True)
    project: Mapped[str | None] = mapped_column(String(30), nullable=True)
    material_pk: Mapped[str | None] = mapped_column(String(25), nullable=True)
    supplier_pk: Mapped[str | None] = mapped_column(String(25), nullable=True)
    supplier_code: Mapped[str | None] = mapped_column(String(50), nullable=True, index=True)
    supplier_name: Mapped[str | None] = mapped_column(String(200), nullable=True)
    pay_term_pk: Mapped[str | None] = mapped_column(String(25), nullable=True)
    tax_rate: Mapped[Decimal | None] = mapped_column(Numeric(9, 4), nullable=True)
    scomment: Mapped[str | None] = mapped_column(String(500), nullable=True)
    src_bill_type: Mapped[str | None] = mapped_column(String(20), nullable=True)
    top_bill_type: Mapped[str | None] = mapped_column(String(20), nullable=True)
    nc_ts: Mapped[str] = mapped_column(String(19), nullable=False)
    synced_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    bill: Mapped[NcApBill] = relationship(back_populates="lines")


class NcApSyncRun(UUIDPrimaryKey, TimestampMixin, Base):
    __tablename__ = "nc_ap_sync_runs"

    mode: Mapped[str] = mapped_column(String(15), nullable=False)      # full | incremental
    status: Mapped[str] = mapped_column(String(10), nullable=False, default=RUNNING, index=True)
    started_by: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    started_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    finished_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    watermark_from: Mapped[str | None] = mapped_column(String(19), nullable=True)
    watermark_to: Mapped[str | None] = mapped_column(String(19), nullable=True)
    bills_seen: Mapped[int] = mapped_column(Integer, nullable=False, default=0, server_default="0")
    bills_upserted: Mapped[int] = mapped_column(Integer, nullable=False, default=0, server_default="0")
    lines_upserted: Mapped[int] = mapped_column(Integer, nullable=False, default=0, server_default="0")
    lines_deleted: Mapped[int] = mapped_column(Integer, nullable=False, default=0, server_default="0")
    payments_upserted: Mapped[int] = mapped_column(Integer, nullable=False, default=0, server_default="0")
    payment_lines_upserted: Mapped[int] = mapped_column(Integer, nullable=False, default=0, server_default="0")
    payment_lines_deleted: Mapped[int] = mapped_column(Integer, nullable=False, default=0, server_default="0")
    tie_out_ok: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    tie_out: Mapped[dict | None] = mapped_column(JSONB, nullable=True)
    error: Mapped[str | None] = mapped_column(Text, nullable=True)


class NcApPayment(UUIDPrimaryKey, TimestampMixin, Base):
    """NC payment document (付款单). Mirrored because the payables alone cannot
    tell you whether a supplier's open balance is real — see 0034's note."""
    __tablename__ = "nc_ap_payments"

    nc_pk: Mapped[str] = mapped_column(String(25), nullable=False, unique=True)
    bill_no: Mapped[str] = mapped_column(String(40), nullable=False, index=True)
    trade_type: Mapped[str | None] = mapped_column(String(30), nullable=True)
    bill_type: Mapped[str | None] = mapped_column(String(20), nullable=True)
    src_syscode: Mapped[int | None] = mapped_column(Integer, nullable=True)
    bill_year: Mapped[str | None] = mapped_column(String(4), nullable=True)
    bill_period: Mapped[str | None] = mapped_column(String(2), nullable=True)
    bill_date: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    pay_date: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True, index=True)
    approve_date: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    bill_status: Mapped[int | None] = mapped_column(Integer, nullable=True)
    approve_status: Mapped[int | None] = mapped_column(Integer, nullable=True)
    currency: Mapped[str | None] = mapped_column(String(10), nullable=True)
    money: Mapped[Decimal | None] = mapped_column(Numeric(18, 2), nullable=True)
    local_money: Mapped[Decimal | None] = mapped_column(Numeric(18, 2), nullable=True)
    invoice_no: Mapped[str | None] = mapped_column(String(100), nullable=True)
    invoice_no_norm: Mapped[str | None] = mapped_column(String(100), nullable=True, index=True)
    settle_flag: Mapped[str | None] = mapped_column(String(10), nullable=True)
    scomment: Mapped[str | None] = mapped_column(String(500), nullable=True)
    nc_ts: Mapped[str] = mapped_column(String(19), nullable=False, index=True)
    synced_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    lines: Mapped[list["NcApPaymentLine"]] = relationship(
        back_populates="payment", cascade="all, delete-orphan", passive_deletes=True)


class NcApPaymentLine(Base):
    __tablename__ = "nc_ap_payment_lines"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True,
                                          default=uuid.uuid4)
    payment_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("nc_ap_payments.id", ondelete="CASCADE"),
        nullable=False, index=True)
    nc_pk: Mapped[str] = mapped_column(String(25), nullable=False, unique=True)
    row_no: Mapped[int | None] = mapped_column(Integer, nullable=True)
    bill_no: Mapped[str] = mapped_column(String(40), nullable=False)
    bill_date: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    pay_date: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    bill_year: Mapped[str | None] = mapped_column(String(4), nullable=True)
    bill_period: Mapped[str | None] = mapped_column(String(2), nullable=True)
    money_de: Mapped[Decimal | None] = mapped_column(Numeric(18, 2), nullable=True)
    money_bal: Mapped[Decimal | None] = mapped_column(Numeric(18, 2), nullable=True)
    local_money_de: Mapped[Decimal | None] = mapped_column(Numeric(18, 2), nullable=True)
    settle_money: Mapped[Decimal | None] = mapped_column(Numeric(18, 2), nullable=True)
    currency: Mapped[str | None] = mapped_column(String(10), nullable=True)
    subject_code: Mapped[str | None] = mapped_column(String(30), nullable=True)
    supplier_pk: Mapped[str | None] = mapped_column(String(25), nullable=True)
    supplier_code: Mapped[str | None] = mapped_column(String(50), nullable=True, index=True)
    supplier_name: Mapped[str | None] = mapped_column(String(200), nullable=True)
    src_bill_type: Mapped[str | None] = mapped_column(String(20), nullable=True)
    src_bill_id: Mapped[str | None] = mapped_column(String(25), nullable=True, index=True)
    top_bill_type: Mapped[str | None] = mapped_column(String(20), nullable=True)
    top_bill_id: Mapped[str | None] = mapped_column(String(25), nullable=True)
    scomment: Mapped[str | None] = mapped_column(String(500), nullable=True)
    nc_ts: Mapped[str] = mapped_column(String(19), nullable=False)
    synced_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)

    payment: Mapped[NcApPayment] = relationship(back_populates="lines")


# Why a stale payable was taken off the working list. Kept as a closed set so
# the reasons can be counted and reported; "other" is the escape hatch and is
# the one case where the note is mandatory (enforced in the API, where the
# message can reach the person typing).
DISMISS_REASONS = {
    "legacy": "Legacy balance — NC period closed, cannot be cleared there",
    "duplicate": "Duplicate document",
    "settled_elsewhere": "Settled outside the AP module (manual journal entry)",
    "written_off": "Written off / no longer payable",
    "other": "Other",
}


class NcApBillDismissal(Base):
    """Finance's judgement that an NC payable is not real debt.

    Mirrors 0035_ap_bill_dismiss column for column. Never joined INTO the
    mirror's own totals — see app/services/ap_ledger_health.py, which reports
    NC's figure and the dismissed figure side by side rather than netting them
    silently.
    """
    __tablename__ = "nc_ap_bill_dismissals"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True,
                                          default=uuid.uuid4)
    bill_no: Mapped[str] = mapped_column(String(40), nullable=False)
    supplier_code: Mapped[str | None] = mapped_column(String(50), nullable=True)
    supplier_name: Mapped[str | None] = mapped_column(String(200), nullable=True)
    currency: Mapped[str | None] = mapped_column(String(10), nullable=True)
    money_bal_at_dismissal: Mapped[Decimal | None] = mapped_column(Numeric(18, 2), nullable=True)
    bill_date: Mapped[date | None] = mapped_column(Date, nullable=True)
    reason: Mapped[str] = mapped_column(String(40), nullable=False)
    note: Mapped[str | None] = mapped_column(Text, nullable=True)
    dismissed_by: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    dismissed_by_name: Mapped[str | None] = mapped_column(String(200), nullable=True)
    dismissed_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    restored_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    restored_by: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    restored_by_name: Mapped[str | None] = mapped_column(String(200), nullable=True)


# Finance's verdict on a duplicate-invoice finding. Closed set for the same
# reason as DISMISS_REASONS: the verdicts get counted. "other" needs a note.
DUP_REVIEW_REASONS = {
    "not_duplicate": "Different invoices that share a number",
    "split": "One invoice deliberately split across several bills",
    "recovered": "Overpayment recovered / credit received from the supplier",
    "correcting_in_nc": "Being corrected in NC (void or credit note pending)",
    "other": "Other",
}


class NcApInvoiceDupReview(Base):
    """Mirrors 0039_ap_inv_dup_reviews column for column. Findings themselves
    are never stored — see app/services/ap_duplicate_invoices.py."""
    __tablename__ = "nc_ap_invoice_dup_reviews"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True,
                                          default=uuid.uuid4)
    finding_key: Mapped[str] = mapped_column(String(300), nullable=False)
    kind: Mapped[str] = mapped_column(String(30), nullable=False)
    invoice_no_norm: Mapped[str] = mapped_column(String(100), nullable=False)
    currency: Mapped[str | None] = mapped_column(String(10), nullable=True)
    supplier_code: Mapped[str | None] = mapped_column(String(50), nullable=True)
    bill_nos: Mapped[list[str]] = mapped_column(ARRAY(String(40)), nullable=False)
    reason: Mapped[str] = mapped_column(String(40), nullable=False)
    note: Mapped[str | None] = mapped_column(Text, nullable=True)
    reviewed_by: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    reviewed_by_name: Mapped[str | None] = mapped_column(String(200), nullable=True)
    reviewed_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    retired_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    retired_by: Mapped[uuid.UUID | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    retired_by_name: Mapped[str | None] = mapped_column(String(200), nullable=True)
