"""NC65 accounts-payable mirror (bills + lines + sync runs).

L0 of the AP work: NC is the book of record for payable balances
(see docs/Finance-Repositioning-And-AP.md §10.1), so everything downstream —
the cash-flow layers, the chain checks, "which of our invoices never made it
into NC" — reads these tables rather than our own paid_amount.

The mirror stays FAITHFUL TO NC: no derived due dates, no synthesised cost
centres, no cleaned-up invoice numbers beyond a normalised search column that
sits ALONGSIDE the raw value. Derivation belongs in the layers above; a mirror
that quietly improves on its source cannot be tied out against it.

Revision ID: 0033_nc_ap_mirror
Revises: 0032_vc_clearing_map
"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import JSONB, UUID

revision = "0033_nc_ap_mirror"
down_revision = "0032_vc_clearing_map"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "nc_ap_bills",
        sa.Column("id", UUID(as_uuid=True), primary_key=True,
                  server_default=sa.text("gen_random_uuid()")),
        # NC identity. nc_pk is the join key for re-sync; bill_no is what humans quote.
        sa.Column("nc_pk", sa.String(25), nullable=False, unique=True),
        sa.Column("bill_no", sa.String(40), nullable=False),
        # The two-worlds discriminator (§9.2): trade_type F1-Cxx-017 + src_syscode 1
        # = keyed by finance; D1 + 4 = generated by the supply chain from a settlement.
        sa.Column("trade_type", sa.String(30), nullable=True),
        sa.Column("bill_type", sa.String(20), nullable=True),
        sa.Column("src_syscode", sa.Integer(), nullable=True),
        sa.Column("bill_class", sa.String(10), nullable=True),
        sa.Column("bill_year", sa.String(4), nullable=True),
        sa.Column("bill_period", sa.String(2), nullable=True),
        sa.Column("bill_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approve_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("effect_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("bill_status", sa.Integer(), nullable=True),
        sa.Column("approve_status", sa.Integer(), nullable=True),
        sa.Column("supplier_pk", sa.String(25), nullable=True),
        sa.Column("supplier_code", sa.String(50), nullable=True),
        sa.Column("supplier_name", sa.String(200), nullable=True),
        sa.Column("currency", sa.String(10), nullable=True),
        sa.Column("money", sa.Numeric(18, 2), nullable=True),
        sa.Column("local_money", sa.Numeric(18, 2), nullable=True),
        sa.Column("bill_maker", sa.String(25), nullable=True),
        # Watermark source. NC's TS is filled on 100% of rows and advances on
        # settlement, so an incremental run does see a bill become fully paid —
        # verified 2026-09-21 before this table was designed.
        sa.Column("nc_ts", sa.String(19), nullable=False),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
    )
    op.create_index("ix_nc_ap_bills_bill_no", "nc_ap_bills", ["bill_no"])
    op.create_index("ix_nc_ap_bills_supplier_code", "nc_ap_bills", ["supplier_code"])
    op.create_index("ix_nc_ap_bills_period", "nc_ap_bills", ["bill_year", "bill_period"])
    op.create_index("ix_nc_ap_bills_nc_ts", "nc_ap_bills", ["nc_ts"])

    op.create_table(
        "nc_ap_bill_lines",
        sa.Column("id", UUID(as_uuid=True), primary_key=True,
                  server_default=sa.text("gen_random_uuid()")),
        sa.Column("bill_id", UUID(as_uuid=True),
                  sa.ForeignKey("nc_ap_bills.id", ondelete="CASCADE"), nullable=False),
        sa.Column("nc_pk", sa.String(25), nullable=False, unique=True),
        sa.Column("row_no", sa.Integer(), nullable=True),
        # Denormalised identity so the checker queries don't need a join.
        sa.Column("bill_no", sa.String(40), nullable=False),
        sa.Column("bill_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("bill_year", sa.String(4), nullable=True),
        sa.Column("bill_period", sa.String(2), nullable=True),
        # money_bal is the whole point of this mirror: it is the authoritative
        # open balance. money_cr is the original credit (tax inclusive).
        sa.Column("money_cr", sa.Numeric(18, 2), nullable=True),
        sa.Column("money_bal", sa.Numeric(18, 2), nullable=True),
        sa.Column("notax_cr", sa.Numeric(18, 2), nullable=True),
        sa.Column("local_money_cr", sa.Numeric(18, 2), nullable=True),
        # invoice_no is the ONLY key that ties an NC bill to one of our invoices
        # and to its voucher (§9.3). Raw value is kept verbatim; _norm is the
        # upper/space-stripped search column — never overwrite the raw one.
        sa.Column("invoice_no", sa.String(100), nullable=True),
        sa.Column("invoice_no_norm", sa.String(100), nullable=True),
        sa.Column("purchase_order", sa.String(60), nullable=True),
        sa.Column("settle_no", sa.String(60), nullable=True),
        sa.Column("contract_no", sa.String(60), nullable=True),
        sa.Column("subject_code", sa.String(30), nullable=True),
        sa.Column("cost_center", sa.String(30), nullable=True),
        sa.Column("dept_pk", sa.String(25), nullable=True),
        sa.Column("dept_code", sa.String(30), nullable=True),
        sa.Column("project", sa.String(30), nullable=True),
        sa.Column("material_pk", sa.String(25), nullable=True),
        sa.Column("supplier_pk", sa.String(25), nullable=True),
        sa.Column("supplier_code", sa.String(50), nullable=True),
        sa.Column("supplier_name", sa.String(200), nullable=True),
        # NC's payment-term pointer, kept verbatim. There is no payment-term
        # master reachable under the NCSC schema (checked 2026-09-21: no
        # BD_PAYTERM / BD_PAYAGREEMENT — only BD_SUPFINANCE references the pk),
        # so name and day-count are deliberately NOT columns here: the due-date
        # rule reads our own vendor terms anyway (§10.2).
        sa.Column("pay_term_pk", sa.String(25), nullable=True),
        sa.Column("tax_rate", sa.Numeric(9, 4), nullable=True),
        sa.Column("scomment", sa.String(500), nullable=True),
        sa.Column("src_bill_type", sa.String(20), nullable=True),
        sa.Column("top_bill_type", sa.String(20), nullable=True),
        sa.Column("nc_ts", sa.String(19), nullable=False),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
    )
    op.create_index("ix_nc_ap_lines_bill_id", "nc_ap_bill_lines", ["bill_id"])
    op.create_index("ix_nc_ap_lines_invoice_norm", "nc_ap_bill_lines", ["invoice_no_norm"])
    op.create_index("ix_nc_ap_lines_po", "nc_ap_bill_lines", ["purchase_order"])
    op.create_index("ix_nc_ap_lines_supplier", "nc_ap_bill_lines", ["supplier_code"])
    # The open-balance working set is small (437 rows in 2026) next to the whole
    # mirror, and every cash-flow query starts from it.
    op.create_index("ix_nc_ap_lines_open", "nc_ap_bill_lines", ["money_bal"],
                    postgresql_where=sa.text("money_bal <> 0"))

    op.create_table(
        "nc_ap_sync_runs",
        sa.Column("id", UUID(as_uuid=True), primary_key=True,
                  server_default=sa.text("gen_random_uuid()")),
        sa.Column("mode", sa.String(15), nullable=False),          # full | incremental
        sa.Column("status", sa.String(10), nullable=False, server_default="running"),
        sa.Column("started_by", UUID(as_uuid=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("watermark_from", sa.String(19), nullable=True),
        sa.Column("watermark_to", sa.String(19), nullable=True),
        sa.Column("bills_seen", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("bills_upserted", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("lines_upserted", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("lines_deleted", sa.Integer(), nullable=False, server_default="0"),
        # Completeness is not optional here (positioning doc §6): every run
        # compares row counts and money totals back against NC and records the
        # answer. A run that cannot tie out is a failed run, not a quiet one.
        sa.Column("tie_out_ok", sa.Boolean(), nullable=True),
        sa.Column("tie_out", JSONB(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
    )
    op.create_index("ix_nc_ap_sync_runs_status", "nc_ap_sync_runs", ["status"])

    # Schedule interval, same contract as nc_jv_sync_interval_minutes:
    # NULL = default, 0 = off.
    op.add_column("company_config",
                  sa.Column("nc_ap_sync_interval_minutes", sa.Integer(), nullable=True))


def downgrade() -> None:
    op.drop_column("company_config", "nc_ap_sync_interval_minutes")
    op.drop_index("ix_nc_ap_sync_runs_status", table_name="nc_ap_sync_runs")
    op.drop_table("nc_ap_sync_runs")
    op.drop_index("ix_nc_ap_lines_open", table_name="nc_ap_bill_lines")
    op.drop_index("ix_nc_ap_lines_supplier", table_name="nc_ap_bill_lines")
    op.drop_index("ix_nc_ap_lines_po", table_name="nc_ap_bill_lines")
    op.drop_index("ix_nc_ap_lines_invoice_norm", table_name="nc_ap_bill_lines")
    op.drop_index("ix_nc_ap_lines_bill_id", table_name="nc_ap_bill_lines")
    op.drop_table("nc_ap_bill_lines")
    op.drop_index("ix_nc_ap_bills_nc_ts", table_name="nc_ap_bills")
    op.drop_index("ix_nc_ap_bills_period", table_name="nc_ap_bills")
    op.drop_index("ix_nc_ap_bills_supplier_code", table_name="nc_ap_bills")
    op.drop_index("ix_nc_ap_bills_bill_no", table_name="nc_ap_bills")
    op.drop_table("nc_ap_bills")
